openapi: 3.0.3
info:
  title: SmileAdventure Auth API
  description: API per l'autenticazione di SmileAdventure
  version: 1.0.0
servers:
  - url: http://localhost:8002/api/v1
    description: Development server
  - url: https://api.smileadventure.com/auth/api/v1
    description: Production server

paths:
  /auth/token:
    post:
      summary: Ottiene un token di accesso
      description: Endopint compatibile con OAuth2 per ottenere un token JWT
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: Email dell'utente
                password:
                  type: string
                  description: Password dell'utente
      responses:
        '200':
          description: Token generato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          description: Credenziali non valide
          
  /auth/login:
    post:
      summary: Effettua il login
      description: Endpoint JSON per ottenere un token JWT
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Login effettuato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          description: Credenziali non valide
          
  /auth/me:
    get:
      summary: Ottiene i dati dell'utente corrente
      description: Restituisce i dati dell'utente associato al token
      tags:
        - auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Operazione completata con successo
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Non autorizzato
          
  /auth/verify-token:
    post:
      summary: Verifica un token JWT
      description: Verifica la validità di un token JWT
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
      responses:
        '200':
          description: Token valido
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Token non valido

components:
  schemas:
    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          
    Token:
      type: object
      required:
        - access_token
        - token_type
      properties:
        access_token:
          type: string
        token_type:
          type: string
          default: bearer
          
    TokenData:
      type: object
      required:
        - user_id
        - role
      properties:
        user_id:
          type: integer
        role:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
