version: '3.8'

services:
  api-gateway:
    build: ./API-GATEWAY
    container_name: smileadventure-api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth
      - users
      - reports # Add dependency if startup order matters, e.g. for health checks
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001/api/v1
      - USERS_SERVICE_URL=http://users-service:8006/api/v1
      - REPORTS_SERVICE_URL=http://reports-service:8007/api/v1 # Added Reports service URL
    networks:
      - smileadventure-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  auth:
    build: ./Auth
    container_name: smileadventure-auth-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./auth.db
      - JWT_SECRET_KEY=your_production_secret_key
      - JWT_EXPIRE_MINUTES=30
    networks:
      - smileadventure-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  users:
    build: ./Users
    container_name: smileadventure-users-service
    ports:
      - "8006:8006"
    environment:
      - DATABASE_URL=sqlite:///./user.db
    networks:
      - smileadventure-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  reports:
    build: ./Reports  # Assuming the Dockerfile is in ./Reports
    container_name: smileadventure-reports-service
    ports:
      - "8007:8007" # Expose port if needed for direct access, or just for gateway
    environment:
      - REPORTS_DATABASE_URL=sqlite:///./reports.db # Or PostgreSQL connection string
      # Add any other necessary environment variables for the Reports service
    networks:
      - smileadventure-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # volumes: # Add volumes if you need to persist data, e.g., for SQLite
      # - ./Reports/data:/app/data # Example for persisting SQLite DB

  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000/api/v1
      - REACT_APP_STRIPE_PUBLIC_KEY=pk_test_51Qwl3g4bGuhP8JnHdmOoePEpNDmuQqc5N9iNOX2esXoc4vnBfxSTYqXHFreVOt0uU0vnsNb4rP56kUw0FYHbiYcN00fJYFxBga
    build:
      context: ./docker-react
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./docker-react:/app
    networks:
      - smileadventure-network
    depends_on:
      - api-gateway

  tests:
    stdin_open: true
    build:
      context: ./docker-react
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./docker-react:/app
    command: ['npm', 'run', 'test']
    networks:
      - smileadventure-network

  er-diagrams:
    image: graphviz/graphviz:latest
    container_name: smileadventure-er-diagrams
    volumes:
      - ./:/app
      - ./docs/diagrams:/app/docs/diagrams
    working_dir: /app
    command: >
      sh -c "
        apt-get update && 
        apt-get install -y python3 python3-pip && 
        pip3 install eralchemy2 sqlalchemy && 
        mkdir -p /app/docs/diagrams &&
        python3 -c 'from scripts.er_model import generate_diagrams; generate_diagrams()'
      "
    networks:
      - smileadventure-network
    depends_on:
      - auth
      - users

  db-init:
    image: python:3.10-slim
    container_name: smileadventure-db-init
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "
        pip install sqlalchemy &&
        python scripts/db_init.py &&
        python scripts/seeds_gen.py
      "
    networks:
      - smileadventure-network

networks:
  smileadventure-network:
    driver: bridge